// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ProtoRequestSyncEntityMessageResponse
	ProtoSyncEntityMessageRequest
	ProtoSyncDataMessagesRequest
	ProtoSyncDataMessageRequest
	ProtoSyncEntityMessageResponse
	ProtoSyncDataMessagesResponse
	ProtoSyncDataMessageResponse
	ProtoRecord
	ProtoField
	ProtoFieldTypeDouble
	ProtoFieldTypeFloat
	ProtoFieldTypeInt32
	ProtoFieldTypeInt64
	ProtoFieldTypeUint32
	ProtoFieldTypeUint64
	ProtoFieldTypeSint32
	ProtoFieldTypeSint64
	ProtoFieldTypeFixed32
	ProtoFieldTypeFixed64
	ProtoFieldTypeSfixed32
	ProtoFieldTypeSfixed64
	ProtoFieldTypeBool
	ProtoFieldTypeString
	ProtoFieldTypeBytes
*/
package syncmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SyncRequestEntityMessageResponseResult int32

const (
	SyncRequestEntityMessageResponseResult_HasMsgs           SyncRequestEntityMessageResponseResult = 1
	SyncRequestEntityMessageResponseResult_NoMsgs            SyncRequestEntityMessageResponseResult = 2
	SyncRequestEntityMessageResponseResult_ErrorCreatingMsgs SyncRequestEntityMessageResponseResult = 3
)

var SyncRequestEntityMessageResponseResult_name = map[int32]string{
	1: "HasMsgs",
	2: "NoMsgs",
	3: "ErrorCreatingMsgs",
}
var SyncRequestEntityMessageResponseResult_value = map[string]int32{
	"HasMsgs":           1,
	"NoMsgs":            2,
	"ErrorCreatingMsgs": 3,
}

func (x SyncRequestEntityMessageResponseResult) Enum() *SyncRequestEntityMessageResponseResult {
	p := new(SyncRequestEntityMessageResponseResult)
	*p = x
	return p
}
func (x SyncRequestEntityMessageResponseResult) String() string {
	return proto.EnumName(SyncRequestEntityMessageResponseResult_name, int32(x))
}
func (x *SyncRequestEntityMessageResponseResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncRequestEntityMessageResponseResult_value, data, "SyncRequestEntityMessageResponseResult")
	if err != nil {
		return err
	}
	*x = SyncRequestEntityMessageResponseResult(value)
	return nil
}
func (SyncRequestEntityMessageResponseResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

type SyncEntityMessageResponseResult int32

const (
	SyncEntityMessageResponseResult_OK    SyncEntityMessageResponseResult = 1
	SyncEntityMessageResponseResult_Error SyncEntityMessageResponseResult = 2
)

var SyncEntityMessageResponseResult_name = map[int32]string{
	1: "OK",
	2: "Error",
}
var SyncEntityMessageResponseResult_value = map[string]int32{
	"OK":    1,
	"Error": 2,
}

func (x SyncEntityMessageResponseResult) Enum() *SyncEntityMessageResponseResult {
	p := new(SyncEntityMessageResponseResult)
	*p = x
	return p
}
func (x SyncEntityMessageResponseResult) String() string {
	return proto.EnumName(SyncEntityMessageResponseResult_name, int32(x))
}
func (x *SyncEntityMessageResponseResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEntityMessageResponseResult_value, data, "SyncEntityMessageResponseResult")
	if err != nil {
		return err
	}
	*x = SyncEntityMessageResponseResult(value)
	return nil
}
func (SyncEntityMessageResponseResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

type SentSyncStateEnum int32

const (
	// COMMENTED OUT
	// Undefined                                             = 0;
	SentSyncStateEnum_PersistedNeverSentToPeer     SentSyncStateEnum = 1
	SentSyncStateEnum_PersistedFirstTimeSentToPeer SentSyncStateEnum = 2
	SentSyncStateEnum_PersistedStandardSentToPeer  SentSyncStateEnum = 3
	SentSyncStateEnum_PersistedFastDeleted         SentSyncStateEnum = 4
)

var SentSyncStateEnum_name = map[int32]string{
	1: "PersistedNeverSentToPeer",
	2: "PersistedFirstTimeSentToPeer",
	3: "PersistedStandardSentToPeer",
	4: "PersistedFastDeleted",
}
var SentSyncStateEnum_value = map[string]int32{
	"PersistedNeverSentToPeer":     1,
	"PersistedFirstTimeSentToPeer": 2,
	"PersistedStandardSentToPeer":  3,
	"PersistedFastDeleted":         4,
}

func (x SentSyncStateEnum) Enum() *SentSyncStateEnum {
	p := new(SentSyncStateEnum)
	*p = x
	return p
}
func (x SentSyncStateEnum) String() string {
	return proto.EnumName(SentSyncStateEnum_name, int32(x))
}
func (x *SentSyncStateEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SentSyncStateEnum_value, data, "SentSyncStateEnum")
	if err != nil {
		return err
	}
	*x = SentSyncStateEnum(value)
	return nil
}
func (SentSyncStateEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AckSyncStateEnum int32

const (
	// COMMENTED OUT
	// Undefined                                             = 0;
	// PersistedNeverSentToPeer                              = 1;
	// PersistedFirstTimeSentToPeer                          = 2;
	// PersistedStandardSentToPeer                           = 3;
	// PersistedFastDeleted                                  = 4;
	AckSyncStateEnum_AckFastBatch                                          AckSyncStateEnum = 21
	AckSyncStateEnum_AckRecordLevelConflictResolvedSeparateFieldsChanged   AckSyncStateEnum = 22
	AckSyncStateEnum_AckFieldLevelConflictwithNoAutoResolverAvailable      AckSyncStateEnum = 23
	AckSyncStateEnum_AckFieldLevelConflictResolvedWithAutoResolver         AckSyncStateEnum = 24
	AckSyncStateEnum_AckFieldLevelConflictWithNoAutoResolverResolution     AckSyncStateEnum = 25
	AckSyncStateEnum_AckDeleteAndUpdateConflictWithNoAutoResolverAvailable AckSyncStateEnum = 26
	AckSyncStateEnum_AckDeleteAndUpdateConflictWithNoAutoResolution        AckSyncStateEnum = 27
	AckSyncStateEnum_AckDeleteAndUpdateConflictWithAutoResolution          AckSyncStateEnum = 28
)

var AckSyncStateEnum_name = map[int32]string{
	21: "AckFastBatch",
	22: "AckRecordLevelConflictResolvedSeparateFieldsChanged",
	23: "AckFieldLevelConflictwithNoAutoResolverAvailable",
	24: "AckFieldLevelConflictResolvedWithAutoResolver",
	25: "AckFieldLevelConflictWithNoAutoResolverResolution",
	26: "AckDeleteAndUpdateConflictWithNoAutoResolverAvailable",
	27: "AckDeleteAndUpdateConflictWithNoAutoResolution",
	28: "AckDeleteAndUpdateConflictWithAutoResolution",
}
var AckSyncStateEnum_value = map[string]int32{
	"AckFastBatch":                                          21,
	"AckRecordLevelConflictResolvedSeparateFieldsChanged":   22,
	"AckFieldLevelConflictwithNoAutoResolverAvailable":      23,
	"AckFieldLevelConflictResolvedWithAutoResolver":         24,
	"AckFieldLevelConflictWithNoAutoResolverResolution":     25,
	"AckDeleteAndUpdateConflictWithNoAutoResolverAvailable": 26,
	"AckDeleteAndUpdateConflictWithNoAutoResolution":        27,
	"AckDeleteAndUpdateConflictWithAutoResolution":          28,
}

func (x AckSyncStateEnum) Enum() *AckSyncStateEnum {
	p := new(AckSyncStateEnum)
	*p = x
	return p
}
func (x AckSyncStateEnum) String() string {
	return proto.EnumName(AckSyncStateEnum_name, int32(x))
}
func (x *AckSyncStateEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AckSyncStateEnum_value, data, "AckSyncStateEnum")
	if err != nil {
		return err
	}
	*x = AckSyncStateEnum(value)
	return nil
}
func (AckSyncStateEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ProtoEncodedFieldType int32

const (
	ProtoEncodedFieldType_DOUBLE   ProtoEncodedFieldType = 0
	ProtoEncodedFieldType_FLOAT    ProtoEncodedFieldType = 1
	ProtoEncodedFieldType_INT32    ProtoEncodedFieldType = 2
	ProtoEncodedFieldType_INT64    ProtoEncodedFieldType = 3
	ProtoEncodedFieldType_UINT32   ProtoEncodedFieldType = 4
	ProtoEncodedFieldType_UINT64   ProtoEncodedFieldType = 5
	ProtoEncodedFieldType_SINT32   ProtoEncodedFieldType = 6
	ProtoEncodedFieldType_SINT64   ProtoEncodedFieldType = 7
	ProtoEncodedFieldType_FIXED32  ProtoEncodedFieldType = 8
	ProtoEncodedFieldType_FIXED64  ProtoEncodedFieldType = 9
	ProtoEncodedFieldType_SFIXED32 ProtoEncodedFieldType = 10
	ProtoEncodedFieldType_SFIXED64 ProtoEncodedFieldType = 11
	ProtoEncodedFieldType_BOOL     ProtoEncodedFieldType = 12
	ProtoEncodedFieldType_STRING   ProtoEncodedFieldType = 13
	ProtoEncodedFieldType_BYTES    ProtoEncodedFieldType = 14
)

var ProtoEncodedFieldType_name = map[int32]string{
	0:  "DOUBLE",
	1:  "FLOAT",
	2:  "INT32",
	3:  "INT64",
	4:  "UINT32",
	5:  "UINT64",
	6:  "SINT32",
	7:  "SINT64",
	8:  "FIXED32",
	9:  "FIXED64",
	10: "SFIXED32",
	11: "SFIXED64",
	12: "BOOL",
	13: "STRING",
	14: "BYTES",
}
var ProtoEncodedFieldType_value = map[string]int32{
	"DOUBLE":   0,
	"FLOAT":    1,
	"INT32":    2,
	"INT64":    3,
	"UINT32":   4,
	"UINT64":   5,
	"SINT32":   6,
	"SINT64":   7,
	"FIXED32":  8,
	"FIXED64":  9,
	"SFIXED32": 10,
	"SFIXED64": 11,
	"BOOL":     12,
	"STRING":   13,
	"BYTES":    14,
}

func (x ProtoEncodedFieldType) Enum() *ProtoEncodedFieldType {
	p := new(ProtoEncodedFieldType)
	*p = x
	return p
}
func (x ProtoEncodedFieldType) String() string {
	return proto.EnumName(ProtoEncodedFieldType_name, int32(x))
}
func (x *ProtoEncodedFieldType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoEncodedFieldType_value, data, "ProtoEncodedFieldType")
	if err != nil {
		return err
	}
	*x = ProtoEncodedFieldType(value)
	return nil
}
func (ProtoEncodedFieldType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ProtoRequestSyncEntityMessageResponse struct {
	Result           *SyncRequestEntityMessageResponseResult `protobuf:"varint,1,req,name=result,enum=SyncRequestEntityMessageResponseResult" json:"result,omitempty"`
	ResultMsg        *string                                 `protobuf:"bytes,2,req,name=result_msg" json:"result_msg,omitempty"`
	Request          *ProtoSyncEntityMessageRequest          `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *ProtoRequestSyncEntityMessageResponse) Reset()         { *m = ProtoRequestSyncEntityMessageResponse{} }
func (m *ProtoRequestSyncEntityMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ProtoRequestSyncEntityMessageResponse) ProtoMessage()    {}
func (*ProtoRequestSyncEntityMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *ProtoRequestSyncEntityMessageResponse) GetResult() SyncRequestEntityMessageResponseResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return SyncRequestEntityMessageResponseResult_HasMsgs
}

func (m *ProtoRequestSyncEntityMessageResponse) GetResultMsg() string {
	if m != nil && m.ResultMsg != nil {
		return *m.ResultMsg
	}
	return ""
}

func (m *ProtoRequestSyncEntityMessageResponse) GetRequest() *ProtoSyncEntityMessageRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type ProtoSyncEntityMessageRequest struct {
	IsDelete          *bool                           `protobuf:"varint,1,req,name=is_delete" json:"is_delete,omitempty"`
	TransactionBindId *string                         `protobuf:"bytes,2,req,name=transaction_bind_id" json:"transaction_bind_id,omitempty"`
	Items             []*ProtoSyncDataMessagesRequest `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *ProtoSyncEntityMessageRequest) Reset()                    { *m = ProtoSyncEntityMessageRequest{} }
func (m *ProtoSyncEntityMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyncEntityMessageRequest) ProtoMessage()               {}
func (*ProtoSyncEntityMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoSyncEntityMessageRequest) GetIsDelete() bool {
	if m != nil && m.IsDelete != nil {
		return *m.IsDelete
	}
	return false
}

func (m *ProtoSyncEntityMessageRequest) GetTransactionBindId() string {
	if m != nil && m.TransactionBindId != nil {
		return *m.TransactionBindId
	}
	return ""
}

func (m *ProtoSyncEntityMessageRequest) GetItems() []*ProtoSyncDataMessagesRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type ProtoSyncDataMessagesRequest struct {
	EntityPluralName *string                        `protobuf:"bytes,1,req,name=entity_plural_name" json:"entity_plural_name,omitempty"`
	Msgs             []*ProtoSyncDataMessageRequest `protobuf:"bytes,2,rep,name=msgs" json:"msgs,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *ProtoSyncDataMessagesRequest) Reset()                    { *m = ProtoSyncDataMessagesRequest{} }
func (m *ProtoSyncDataMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyncDataMessagesRequest) ProtoMessage()               {}
func (*ProtoSyncDataMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtoSyncDataMessagesRequest) GetEntityPluralName() string {
	if m != nil && m.EntityPluralName != nil {
		return *m.EntityPluralName
	}
	return ""
}

func (m *ProtoSyncDataMessagesRequest) GetMsgs() []*ProtoSyncDataMessageRequest {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type ProtoSyncDataMessageRequest struct {
	RecordId          *string            `protobuf:"bytes,1,req,name=record_id" json:"record_id,omitempty"`
	RecordHash        *string            `protobuf:"bytes,2,req,name=record_hash" json:"record_hash,omitempty"`
	LastKnownPeerHash *string            `protobuf:"bytes,3,opt,name=last_known_peer_hash" json:"last_known_peer_hash,omitempty"`
	SentSyncState     *SentSyncStateEnum `protobuf:"varint,4,req,name=sent_sync_state,enum=SentSyncStateEnum" json:"sent_sync_state,omitempty"`
	RecordBytesSize   *uint32            `protobuf:"varint,5,req,name=record_bytes_size" json:"record_bytes_size,omitempty"`
	RecordData        []byte             `protobuf:"bytes,6,req,name=record_data" json:"record_data,omitempty"`
	XXX_unrecognized  []byte             `json:"-"`
}

func (m *ProtoSyncDataMessageRequest) Reset()                    { *m = ProtoSyncDataMessageRequest{} }
func (m *ProtoSyncDataMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyncDataMessageRequest) ProtoMessage()               {}
func (*ProtoSyncDataMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoSyncDataMessageRequest) GetRecordId() string {
	if m != nil && m.RecordId != nil {
		return *m.RecordId
	}
	return ""
}

func (m *ProtoSyncDataMessageRequest) GetRecordHash() string {
	if m != nil && m.RecordHash != nil {
		return *m.RecordHash
	}
	return ""
}

func (m *ProtoSyncDataMessageRequest) GetLastKnownPeerHash() string {
	if m != nil && m.LastKnownPeerHash != nil {
		return *m.LastKnownPeerHash
	}
	return ""
}

func (m *ProtoSyncDataMessageRequest) GetSentSyncState() SentSyncStateEnum {
	if m != nil && m.SentSyncState != nil {
		return *m.SentSyncState
	}
	return SentSyncStateEnum_PersistedNeverSentToPeer
}

func (m *ProtoSyncDataMessageRequest) GetRecordBytesSize() uint32 {
	if m != nil && m.RecordBytesSize != nil {
		return *m.RecordBytesSize
	}
	return 0
}

func (m *ProtoSyncDataMessageRequest) GetRecordData() []byte {
	if m != nil {
		return m.RecordData
	}
	return nil
}

type ProtoSyncEntityMessageResponse struct {
	TransactionBindId *string                          `protobuf:"bytes,1,req,name=transaction_bind_id" json:"transaction_bind_id,omitempty"`
	Items             []*ProtoSyncDataMessagesResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Result            *SyncEntityMessageResponseResult `protobuf:"varint,3,req,name=result,enum=SyncEntityMessageResponseResult" json:"result,omitempty"`
	ResultMsg         *string                          `protobuf:"bytes,4,req,name=result_msg" json:"result_msg,omitempty"`
	XXX_unrecognized  []byte                           `json:"-"`
}

func (m *ProtoSyncEntityMessageResponse) Reset()                    { *m = ProtoSyncEntityMessageResponse{} }
func (m *ProtoSyncEntityMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyncEntityMessageResponse) ProtoMessage()               {}
func (*ProtoSyncEntityMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProtoSyncEntityMessageResponse) GetTransactionBindId() string {
	if m != nil && m.TransactionBindId != nil {
		return *m.TransactionBindId
	}
	return ""
}

func (m *ProtoSyncEntityMessageResponse) GetItems() []*ProtoSyncDataMessagesResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ProtoSyncEntityMessageResponse) GetResult() SyncEntityMessageResponseResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return SyncEntityMessageResponseResult_OK
}

func (m *ProtoSyncEntityMessageResponse) GetResultMsg() string {
	if m != nil && m.ResultMsg != nil {
		return *m.ResultMsg
	}
	return ""
}

type ProtoSyncDataMessagesResponse struct {
	EntityPluralName *string                         `protobuf:"bytes,1,req,name=entity_plural_name" json:"entity_plural_name,omitempty"`
	Msgs             []*ProtoSyncDataMessageResponse `protobuf:"bytes,2,rep,name=msgs" json:"msgs,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ProtoSyncDataMessagesResponse) Reset()                    { *m = ProtoSyncDataMessagesResponse{} }
func (m *ProtoSyncDataMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyncDataMessagesResponse) ProtoMessage()               {}
func (*ProtoSyncDataMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProtoSyncDataMessagesResponse) GetEntityPluralName() string {
	if m != nil && m.EntityPluralName != nil {
		return *m.EntityPluralName
	}
	return ""
}

func (m *ProtoSyncDataMessagesResponse) GetMsgs() []*ProtoSyncDataMessageResponse {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type ProtoSyncDataMessageResponse struct {
	RecordId *string `protobuf:"bytes,1,req,name=record_id" json:"record_id,omitempty"`
	// If the request hash is not present, than the sync_state must be AckedFastBatch or
	// AckedRecordLevelConflictResolvedSeparateFieldsChanged. If not, than all optional value
	// must be present.
	RequestHash  *string           `protobuf:"bytes,2,opt,name=request_hash" json:"request_hash,omitempty"`
	ResponseHash *string           `protobuf:"bytes,3,req,name=response_hash" json:"response_hash,omitempty"`
	SyncState    *AckSyncStateEnum `protobuf:"varint,4,req,name=sync_state,enum=AckSyncStateEnum" json:"sync_state,omitempty"`
	// If the request hash is not present, than the sync_state must be AckedFastBatch or
	// AckedRecordLevelConflictResolvedSeparateFieldsChanged. If not, than all optional value
	// must be present.
	RecordBytesSize *uint32 `protobuf:"varint,5,opt,name=record_bytes_size" json:"record_bytes_size,omitempty"`
	// If the request hash is not present, than the sync_state must be AckedFastBatch or
	// AckedRecordLevelConflictResolvedSeparateFieldsChanged. If not, than all optional value
	// must be present.
	RecordData       []byte `protobuf:"bytes,6,opt,name=record_data" json:"record_data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoSyncDataMessageResponse) Reset()                    { *m = ProtoSyncDataMessageResponse{} }
func (m *ProtoSyncDataMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyncDataMessageResponse) ProtoMessage()               {}
func (*ProtoSyncDataMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ProtoSyncDataMessageResponse) GetRecordId() string {
	if m != nil && m.RecordId != nil {
		return *m.RecordId
	}
	return ""
}

func (m *ProtoSyncDataMessageResponse) GetRequestHash() string {
	if m != nil && m.RequestHash != nil {
		return *m.RequestHash
	}
	return ""
}

func (m *ProtoSyncDataMessageResponse) GetResponseHash() string {
	if m != nil && m.ResponseHash != nil {
		return *m.ResponseHash
	}
	return ""
}

func (m *ProtoSyncDataMessageResponse) GetSyncState() AckSyncStateEnum {
	if m != nil && m.SyncState != nil {
		return *m.SyncState
	}
	return AckSyncStateEnum_AckFastBatch
}

func (m *ProtoSyncDataMessageResponse) GetRecordBytesSize() uint32 {
	if m != nil && m.RecordBytesSize != nil {
		return *m.RecordBytesSize
	}
	return 0
}

func (m *ProtoSyncDataMessageResponse) GetRecordData() []byte {
	if m != nil {
		return m.RecordData
	}
	return nil
}

type ProtoRecord struct {
	Fields           []*ProtoField `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ProtoRecord) Reset()                    { *m = ProtoRecord{} }
func (m *ProtoRecord) String() string            { return proto.CompactTextString(m) }
func (*ProtoRecord) ProtoMessage()               {}
func (*ProtoRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProtoRecord) GetFields() []*ProtoField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ProtoField struct {
	EncodedFieldType *ProtoEncodedFieldType `protobuf:"varint,1,req,name=encoded_field_type,enum=ProtoEncodedFieldType" json:"encoded_field_type,omitempty"`
	FieldName        *string                `protobuf:"bytes,2,req,name=field_name" json:"field_name,omitempty"`
	FieldValue       []byte                 `protobuf:"bytes,3,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ProtoField) Reset()                    { *m = ProtoField{} }
func (m *ProtoField) String() string            { return proto.CompactTextString(m) }
func (*ProtoField) ProtoMessage()               {}
func (*ProtoField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ProtoField) GetEncodedFieldType() ProtoEncodedFieldType {
	if m != nil && m.EncodedFieldType != nil {
		return *m.EncodedFieldType
	}
	return ProtoEncodedFieldType_DOUBLE
}

func (m *ProtoField) GetFieldName() string {
	if m != nil && m.FieldName != nil {
		return *m.FieldName
	}
	return ""
}

func (m *ProtoField) GetFieldValue() []byte {
	if m != nil {
		return m.FieldValue
	}
	return nil
}

// FieldType 0
type ProtoFieldTypeDouble struct {
	FieldValue       *float64 `protobuf:"fixed64,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoFieldTypeDouble) Reset()                    { *m = ProtoFieldTypeDouble{} }
func (m *ProtoFieldTypeDouble) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeDouble) ProtoMessage()               {}
func (*ProtoFieldTypeDouble) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ProtoFieldTypeDouble) GetFieldValue() float64 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 1
type ProtoFieldTypeFloat struct {
	FieldValue       *float32 `protobuf:"fixed32,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoFieldTypeFloat) Reset()                    { *m = ProtoFieldTypeFloat{} }
func (m *ProtoFieldTypeFloat) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeFloat) ProtoMessage()               {}
func (*ProtoFieldTypeFloat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ProtoFieldTypeFloat) GetFieldValue() float32 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 2
type ProtoFieldTypeInt32 struct {
	FieldValue       *int32 `protobuf:"varint,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeInt32) Reset()                    { *m = ProtoFieldTypeInt32{} }
func (m *ProtoFieldTypeInt32) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeInt32) ProtoMessage()               {}
func (*ProtoFieldTypeInt32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ProtoFieldTypeInt32) GetFieldValue() int32 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 3
type ProtoFieldTypeInt64 struct {
	FieldValue       *int64 `protobuf:"varint,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeInt64) Reset()                    { *m = ProtoFieldTypeInt64{} }
func (m *ProtoFieldTypeInt64) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeInt64) ProtoMessage()               {}
func (*ProtoFieldTypeInt64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ProtoFieldTypeInt64) GetFieldValue() int64 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 4
type ProtoFieldTypeUint32 struct {
	FieldValue       *uint32 `protobuf:"varint,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoFieldTypeUint32) Reset()                    { *m = ProtoFieldTypeUint32{} }
func (m *ProtoFieldTypeUint32) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeUint32) ProtoMessage()               {}
func (*ProtoFieldTypeUint32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ProtoFieldTypeUint32) GetFieldValue() uint32 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 5
type ProtoFieldTypeUint64 struct {
	FieldValue       *uint64 `protobuf:"varint,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoFieldTypeUint64) Reset()                    { *m = ProtoFieldTypeUint64{} }
func (m *ProtoFieldTypeUint64) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeUint64) ProtoMessage()               {}
func (*ProtoFieldTypeUint64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ProtoFieldTypeUint64) GetFieldValue() uint64 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 6
type ProtoFieldTypeSint32 struct {
	FieldValue       *int32 `protobuf:"zigzag32,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeSint32) Reset()                    { *m = ProtoFieldTypeSint32{} }
func (m *ProtoFieldTypeSint32) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeSint32) ProtoMessage()               {}
func (*ProtoFieldTypeSint32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ProtoFieldTypeSint32) GetFieldValue() int32 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 7
type ProtoFieldTypeSint64 struct {
	FieldValue       *int64 `protobuf:"zigzag64,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeSint64) Reset()                    { *m = ProtoFieldTypeSint64{} }
func (m *ProtoFieldTypeSint64) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeSint64) ProtoMessage()               {}
func (*ProtoFieldTypeSint64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ProtoFieldTypeSint64) GetFieldValue() int64 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 8
type ProtoFieldTypeFixed32 struct {
	FieldValue       *uint32 `protobuf:"fixed32,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoFieldTypeFixed32) Reset()                    { *m = ProtoFieldTypeFixed32{} }
func (m *ProtoFieldTypeFixed32) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeFixed32) ProtoMessage()               {}
func (*ProtoFieldTypeFixed32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ProtoFieldTypeFixed32) GetFieldValue() uint32 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 9
type ProtoFieldTypeFixed64 struct {
	FieldValue       *uint64 `protobuf:"fixed64,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoFieldTypeFixed64) Reset()                    { *m = ProtoFieldTypeFixed64{} }
func (m *ProtoFieldTypeFixed64) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeFixed64) ProtoMessage()               {}
func (*ProtoFieldTypeFixed64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ProtoFieldTypeFixed64) GetFieldValue() uint64 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 10
type ProtoFieldTypeSfixed32 struct {
	FieldValue       *int32 `protobuf:"fixed32,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeSfixed32) Reset()                    { *m = ProtoFieldTypeSfixed32{} }
func (m *ProtoFieldTypeSfixed32) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeSfixed32) ProtoMessage()               {}
func (*ProtoFieldTypeSfixed32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ProtoFieldTypeSfixed32) GetFieldValue() int32 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 11
type ProtoFieldTypeSfixed64 struct {
	FieldValue       *int64 `protobuf:"fixed64,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeSfixed64) Reset()                    { *m = ProtoFieldTypeSfixed64{} }
func (m *ProtoFieldTypeSfixed64) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeSfixed64) ProtoMessage()               {}
func (*ProtoFieldTypeSfixed64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ProtoFieldTypeSfixed64) GetFieldValue() int64 {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return 0
}

// FieldType 12
type ProtoFieldTypeBool struct {
	FieldValue       *bool  `protobuf:"varint,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeBool) Reset()                    { *m = ProtoFieldTypeBool{} }
func (m *ProtoFieldTypeBool) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeBool) ProtoMessage()               {}
func (*ProtoFieldTypeBool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ProtoFieldTypeBool) GetFieldValue() bool {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return false
}

// FieldType 13
type ProtoFieldTypeString struct {
	FieldValue       *string `protobuf:"bytes,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoFieldTypeString) Reset()                    { *m = ProtoFieldTypeString{} }
func (m *ProtoFieldTypeString) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeString) ProtoMessage()               {}
func (*ProtoFieldTypeString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ProtoFieldTypeString) GetFieldValue() string {
	if m != nil && m.FieldValue != nil {
		return *m.FieldValue
	}
	return ""
}

// FieldType 14
type ProtoFieldTypeBytes struct {
	FieldValue       []byte `protobuf:"bytes,1,req,name=field_value" json:"field_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoFieldTypeBytes) Reset()                    { *m = ProtoFieldTypeBytes{} }
func (m *ProtoFieldTypeBytes) String() string            { return proto.CompactTextString(m) }
func (*ProtoFieldTypeBytes) ProtoMessage()               {}
func (*ProtoFieldTypeBytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ProtoFieldTypeBytes) GetFieldValue() []byte {
	if m != nil {
		return m.FieldValue
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoRequestSyncEntityMessageResponse)(nil), "ProtoRequestSyncEntityMessageResponse")
	proto.RegisterType((*ProtoSyncEntityMessageRequest)(nil), "ProtoSyncEntityMessageRequest")
	proto.RegisterType((*ProtoSyncDataMessagesRequest)(nil), "ProtoSyncDataMessagesRequest")
	proto.RegisterType((*ProtoSyncDataMessageRequest)(nil), "ProtoSyncDataMessageRequest")
	proto.RegisterType((*ProtoSyncEntityMessageResponse)(nil), "ProtoSyncEntityMessageResponse")
	proto.RegisterType((*ProtoSyncDataMessagesResponse)(nil), "ProtoSyncDataMessagesResponse")
	proto.RegisterType((*ProtoSyncDataMessageResponse)(nil), "ProtoSyncDataMessageResponse")
	proto.RegisterType((*ProtoRecord)(nil), "ProtoRecord")
	proto.RegisterType((*ProtoField)(nil), "ProtoField")
	proto.RegisterType((*ProtoFieldTypeDouble)(nil), "ProtoFieldTypeDouble")
	proto.RegisterType((*ProtoFieldTypeFloat)(nil), "ProtoFieldTypeFloat")
	proto.RegisterType((*ProtoFieldTypeInt32)(nil), "ProtoFieldTypeInt32")
	proto.RegisterType((*ProtoFieldTypeInt64)(nil), "ProtoFieldTypeInt64")
	proto.RegisterType((*ProtoFieldTypeUint32)(nil), "ProtoFieldTypeUint32")
	proto.RegisterType((*ProtoFieldTypeUint64)(nil), "ProtoFieldTypeUint64")
	proto.RegisterType((*ProtoFieldTypeSint32)(nil), "ProtoFieldTypeSint32")
	proto.RegisterType((*ProtoFieldTypeSint64)(nil), "ProtoFieldTypeSint64")
	proto.RegisterType((*ProtoFieldTypeFixed32)(nil), "ProtoFieldTypeFixed32")
	proto.RegisterType((*ProtoFieldTypeFixed64)(nil), "ProtoFieldTypeFixed64")
	proto.RegisterType((*ProtoFieldTypeSfixed32)(nil), "ProtoFieldTypeSfixed32")
	proto.RegisterType((*ProtoFieldTypeSfixed64)(nil), "ProtoFieldTypeSfixed64")
	proto.RegisterType((*ProtoFieldTypeBool)(nil), "ProtoFieldTypeBool")
	proto.RegisterType((*ProtoFieldTypeString)(nil), "ProtoFieldTypeString")
	proto.RegisterType((*ProtoFieldTypeBytes)(nil), "ProtoFieldTypeBytes")
	proto.RegisterEnum("SyncRequestEntityMessageResponseResult", SyncRequestEntityMessageResponseResult_name, SyncRequestEntityMessageResponseResult_value)
	proto.RegisterEnum("SyncEntityMessageResponseResult", SyncEntityMessageResponseResult_name, SyncEntityMessageResponseResult_value)
	proto.RegisterEnum("SentSyncStateEnum", SentSyncStateEnum_name, SentSyncStateEnum_value)
	proto.RegisterEnum("AckSyncStateEnum", AckSyncStateEnum_name, AckSyncStateEnum_value)
	proto.RegisterEnum("ProtoEncodedFieldType", ProtoEncodedFieldType_name, ProtoEncodedFieldType_value)
}

var fileDescriptor0 = []byte{
	// 1058 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x52, 0x1b, 0x47,
	0x10, 0xce, 0x4a, 0x42, 0xa0, 0x96, 0xc0, 0xab, 0xe1, 0x27, 0xb2, 0xf9, 0x31, 0xb5, 0x55, 0x4e,
	0x1c, 0x01, 0x8a, 0x0d, 0xd8, 0xa9, 0x1c, 0x11, 0x88, 0x84, 0x0a, 0x06, 0x0a, 0x89, 0xb2, 0x73,
	0xda, 0x5a, 0xb4, 0x03, 0xda, 0xf2, 0x6a, 0x57, 0x99, 0x19, 0xe1, 0x90, 0xaa, 0xbc, 0x42, 0x1e,
	0x21, 0xb7, 0xbc, 0x40, 0xaa, 0x72, 0xcf, 0x3d, 0x2f, 0x95, 0x9e, 0x99, 0x5d, 0xfe, 0x34, 0x2b,
	0x73, 0x62, 0xd5, 0xfd, 0xf5, 0xf7, 0x75, 0x4f, 0xf7, 0xf4, 0x00, 0x33, 0x7d, 0xca, 0xb9, 0x77,
	0x49, 0x79, 0x63, 0xc0, 0x62, 0x11, 0x3b, 0x7f, 0x59, 0xf0, 0xe2, 0x44, 0x7e, 0x9d, 0xd2, 0x5f,
	0x86, 0x94, 0x8b, 0xf6, 0x75, 0xd4, 0x6d, 0x45, 0x22, 0x10, 0xd7, 0xef, 0x34, 0xf0, 0x94, 0xf2,
	0x41, 0x1c, 0x71, 0x4a, 0xbe, 0x83, 0x22, 0xa3, 0x7c, 0x18, 0x8a, 0x9a, 0xb5, 0x9a, 0x7b, 0x39,
	0xb3, 0xf9, 0x75, 0x43, 0x62, 0x93, 0x30, 0x63, 0xc8, 0xa9, 0x82, 0x13, 0x02, 0xa0, 0x03, 0xdd,
	0x3e, 0xbf, 0xac, 0xe5, 0x30, 0xb8, 0x44, 0xbe, 0x85, 0x49, 0xa6, 0x23, 0x6b, 0xf9, 0x55, 0xeb,
	0x65, 0x79, 0x73, 0xa5, 0xa1, 0xb2, 0x30, 0xc8, 0x2b, 0x94, 0xf3, 0x3b, 0x2c, 0x8f, 0x05, 0x90,
	0x2a, 0x94, 0x02, 0xee, 0xfa, 0x34, 0xa4, 0x82, 0xaa, 0x0c, 0xa7, 0xc8, 0x22, 0xcc, 0x0a, 0xe6,
	0x45, 0xdc, 0xeb, 0x8a, 0x20, 0x8e, 0xdc, 0xf3, 0x20, 0xf2, 0xdd, 0xc0, 0x4f, 0x32, 0x58, 0x87,
	0x89, 0x40, 0xd0, 0x3e, 0x47, 0xfd, 0x3c, 0xea, 0x2f, 0xdf, 0xea, 0xef, 0x79, 0xc2, 0x4b, 0xc8,
	0x79, 0x2a, 0x7f, 0x01, 0x4b, 0xe3, 0xfc, 0xe4, 0x19, 0x10, 0xaa, 0xb2, 0x72, 0x07, 0xe1, 0x90,
	0x79, 0xa1, 0x1b, 0x79, 0x7d, 0x9d, 0x46, 0x89, 0xd4, 0xa1, 0x80, 0x85, 0x73, 0xd4, 0x95, 0x42,
	0x4b, 0x46, 0xa1, 0x54, 0xe7, 0x5f, 0x0b, 0x16, 0xc7, 0xf8, 0x65, 0x95, 0x8c, 0x76, 0x63, 0xa6,
	0x0a, 0xd1, 0xf4, 0xb3, 0x50, 0x4e, 0x4c, 0x3d, 0x8f, 0xf7, 0x92, 0xea, 0x96, 0x60, 0x2e, 0xf4,
	0xb8, 0x70, 0x3f, 0x46, 0xf1, 0xa7, 0xc8, 0x1d, 0x50, 0xca, 0xb4, 0x57, 0x1e, 0x76, 0x89, 0xac,
	0xc1, 0x13, 0x8e, 0xe9, 0xba, 0x1c, 0x45, 0x5c, 0x2e, 0x3c, 0x3c, 0xb1, 0x82, 0xea, 0x29, 0x69,
	0xb4, 0xd1, 0x2e, 0xb5, 0xdb, 0xd2, 0xda, 0x8a, 0x86, 0x7d, 0xf2, 0x14, 0xaa, 0x09, 0xff, 0xf9,
	0xb5, 0xa0, 0xdc, 0xe5, 0xc1, 0x6f, 0xb4, 0x36, 0x81, 0xf0, 0xe9, 0x3b, 0xd2, 0x3e, 0xa6, 0x5a,
	0x2b, 0xa2, 0xb1, 0xe2, 0xfc, 0x6d, 0xc1, 0x4a, 0x56, 0xab, 0x92, 0x51, 0xca, 0x68, 0x8c, 0xae,
	0x67, 0x23, 0x6d, 0x8c, 0x3e, 0xaf, 0x95, 0xac, 0xc6, 0x24, 0x5c, 0xaf, 0x6e, 0xc6, 0x32, 0xaf,
	0x4a, 0x58, 0x6d, 0x64, 0xea, 0x1a, 0xe7, 0x51, 0x16, 0x5e, 0x72, 0x7a, 0x77, 0xc6, 0xcb, 0x28,
	0x33, 0xae, 0xc1, 0x6b, 0xf7, 0x1a, 0xbc, 0x9c, 0xd1, 0x60, 0x4d, 0xe4, 0xfc, 0x63, 0x99, 0x47,
	0xe9, 0x46, 0xc9, 0xd0, 0xe2, 0x39, 0xa8, 0x24, 0xb7, 0x25, 0xed, 0xb1, 0xec, 0xe2, 0x3c, 0x4c,
	0xb3, 0x24, 0x28, 0x6d, 0xae, 0x04, 0xbf, 0x00, 0x18, 0xe9, 0x6b, 0xb5, 0xb1, 0xd3, 0xfd, 0xf8,
	0xa8, 0xb6, 0x5a, 0xa6, 0xb6, 0x5a, 0xd8, 0xd6, 0x3a, 0x94, 0x93, 0x3d, 0x21, 0x3d, 0xd8, 0xc2,
	0xe2, 0x45, 0x40, 0x43, 0x9f, 0x63, 0x8a, 0xb2, 0xea, 0xb2, 0xae, 0x7a, 0x5f, 0xda, 0x9c, 0x00,
	0xe0, 0xf6, 0x17, 0xd9, 0x94, 0x47, 0xd7, 0x8d, 0x7d, 0xea, 0xbb, 0x2a, 0xc4, 0x15, 0xd7, 0x03,
	0x9a, 0x2c, 0x91, 0x05, 0x1d, 0xd6, 0xd2, 0x7e, 0x85, 0xef, 0xa0, 0x57, 0xf6, 0x48, 0x63, 0xd5,
	0x31, 0xe7, 0xd2, 0x41, 0xd7, 0xb6, 0x2b, 0x2f, 0x1c, 0x52, 0x55, 0x6d, 0xc5, 0x59, 0x83, 0xb9,
	0x5b, 0x29, 0x19, 0xba, 0x17, 0x0f, 0xcf, 0x43, 0xfa, 0x10, 0x2c, 0xd5, 0x2c, 0xac, 0x61, 0xf6,
	0x3e, 0x78, 0x3f, 0x8c, 0x3d, 0x61, 0xc2, 0xe6, 0x46, 0xb1, 0x07, 0x91, 0xd8, 0xda, 0x34, 0x61,
	0x27, 0x8c, 0xd8, 0xb7, 0xdb, 0x26, 0x6c, 0x7e, 0x34, 0xe1, 0xb3, 0x20, 0x8b, 0x78, 0xda, 0x0c,
	0x36, 0x33, 0x17, 0x46, 0xc1, 0xed, 0x4c, 0xe6, 0xaa, 0x19, 0x6c, 0x66, 0x26, 0xce, 0x3a, 0xcc,
	0x3f, 0x38, 0xb7, 0xe0, 0x57, 0xea, 0x9b, 0xa9, 0x27, 0x33, 0xd0, 0x66, 0xee, 0xa2, 0xb3, 0x01,
	0x0b, 0x0f, 0x12, 0xb9, 0xc8, 0x26, 0x7f, 0x92, 0x05, 0x37, 0xb3, 0xdb, 0xce, 0x37, 0x40, 0xee,
	0xc3, 0x9b, 0x71, 0x1c, 0x9a, 0xa0, 0x53, 0x86, 0x13, 0x11, 0x2c, 0x88, 0x2e, 0x4d, 0xe0, 0xd2,
	0x68, 0xc7, 0x9b, 0xf2, 0x12, 0x99, 0xb0, 0x95, 0xfa, 0x07, 0xf8, 0xea, 0x91, 0x2f, 0x65, 0x19,
	0x26, 0x7f, 0xf4, 0xf8, 0x3b, 0xdc, 0x25, 0xb6, 0x85, 0x37, 0xa0, 0x78, 0x14, 0xab, 0xef, 0x1c,
	0x5e, 0xf5, 0x6a, 0x8b, 0xb1, 0x98, 0xed, 0x32, 0xea, 0x09, 0x4c, 0x4a, 0x99, 0xf3, 0xf5, 0x6d,
	0x78, 0xfe, 0xb9, 0x65, 0x57, 0x84, 0xdc, 0xf1, 0x4f, 0xc8, 0x56, 0x82, 0x09, 0xc5, 0x60, 0xe7,
	0xea, 0x7f, 0x58, 0x50, 0x1d, 0x5d, 0xf3, 0x4b, 0x50, 0x3b, 0xa1, 0x8c, 0x07, 0x5c, 0x50, 0xff,
	0x88, 0x5e, 0x51, 0x26, 0x21, 0x9d, 0xf8, 0x04, 0x9f, 0x0e, 0x0c, 0x5f, 0xc5, 0xa5, 0x95, 0x7a,
	0xf7, 0x03, 0xc6, 0x45, 0x27, 0xe8, 0xd3, 0x3b, 0x88, 0x1c, 0x79, 0x8e, 0x0f, 0x57, 0x8a, 0x40,
	0xd6, 0xc8, 0xf7, 0x98, 0x7f, 0x07, 0x90, 0x27, 0x35, 0x3c, 0xdf, 0x1b, 0x0a, 0x7c, 0x9b, 0xf6,
	0xd4, 0x53, 0xed, 0xdb, 0x85, 0xfa, 0x9f, 0x79, 0xb0, 0x47, 0xf6, 0x93, 0x0d, 0x15, 0xb4, 0x49,
	0x60, 0xd3, 0x13, 0xdd, 0x9e, 0x3d, 0x8f, 0xff, 0x80, 0x6c, 0xa1, 0x45, 0xef, 0x9f, 0x43, 0xcc,
	0x30, 0xdc, 0x8d, 0xa3, 0x8b, 0x30, 0xe8, 0x0a, 0x2c, 0x35, 0x0e, 0xaf, 0x50, 0x96, 0x0e, 0x3c,
	0x86, 0xf1, 0xaa, 0x29, 0x7c, 0xb7, 0xe7, 0x45, 0x97, 0xc8, 0xbf, 0x40, 0xb6, 0xe1, 0x95, 0xa4,
	0x92, 0xd6, 0x7b, 0x71, 0x9f, 0x02, 0xd1, 0x3b, 0x8a, 0x77, 0x86, 0x72, 0xa9, 0x29, 0x06, 0xb6,
	0x73, 0xe5, 0x05, 0xa1, 0x87, 0xfb, 0xc3, 0xfe, 0x92, 0xbc, 0x86, 0x0d, 0x63, 0x54, 0xaa, 0xf6,
	0x1e, 0xa3, 0xef, 0xc6, 0xda, 0x35, 0xf2, 0x06, 0x5e, 0x1b, 0x43, 0xde, 0x8f, 0x08, 0xa9, 0xbf,
	0x43, 0xf9, 0xfa, 0xd9, 0x4f, 0xc9, 0xf7, 0xf0, 0x06, 0xc3, 0xf4, 0x79, 0xec, 0x44, 0xfe, 0xd9,
	0x00, 0xd7, 0x2e, 0xcd, 0x8e, 0xbd, 0x4d, 0xf2, 0x19, 0xee, 0xd6, 0xc6, 0xa3, 0x43, 0xb5, 0xdc,
	0x22, 0xbe, 0x98, 0xeb, 0xe3, 0x63, 0x1e, 0x44, 0x2c, 0xd5, 0xff, 0xb3, 0x92, 0x2b, 0x3d, 0xb2,
	0xa7, 0x71, 0x48, 0xf7, 0x8e, 0xcf, 0x9a, 0x87, 0x2d, 0xfb, 0x0b, 0x39, 0x62, 0xfb, 0x87, 0xc7,
	0x3b, 0x1d, 0x3d, 0x6d, 0x07, 0x47, 0x9d, 0xad, 0x4d, 0x9c, 0x0b, 0xfd, 0xf9, 0x76, 0x1b, 0x27,
	0x00, 0xc1, 0x67, 0xda, 0x5c, 0x48, 0xbf, 0xd1, 0x3e, 0x21, 0xbf, 0xdb, 0xda, 0x5e, 0x4c, 0xbf,
	0xd1, 0x3e, 0x29, 0xaf, 0xc3, 0xfe, 0xc1, 0x87, 0xd6, 0x1e, 0x3a, 0xa6, 0x6e, 0x7e, 0xa0, 0xa7,
	0x44, 0x2a, 0x30, 0xd5, 0x4e, 0x5d, 0x70, 0xfb, 0x0b, 0x7d, 0x65, 0x32, 0x05, 0x85, 0xe6, 0xf1,
	0xf1, 0xa1, 0x5d, 0x51, 0x5c, 0x9d, 0xd3, 0x83, 0xa3, 0x1f, 0xec, 0x69, 0x99, 0x46, 0xf3, 0xe7,
	0x4e, 0xab, 0x6d, 0xcf, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x67, 0x6f, 0x7a, 0x03, 0x0b,
	0x00, 0x00,
}
